# Generated by Django 3.2.11 on 2022-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync_data_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSyncSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('data', models.JSONField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
            ],
        ),
    ]
