# Generated by Django 3.2.11 on 2022-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync_data_report', '0002_clientsyncsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsyncsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientsyncsummary',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
