# Generated by Django 3.2.11 on 2022-04-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edc_sync_data_report', '0004_auto_20220402_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncapis',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='syncmodels',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='syncsite',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='syncstudy',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='syncapis',
            name='sync_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_sync_data_report.syncsite'),
        ),
    ]
